FROM scratch

ADD rootfs_alt_systemd.tar.xz /

LABEL org.opencontainers.image.licenses="GPLv3"

ENV container=podman
VOLUME [ "/sys/fs/cgroup" ]
STOPSIGNAL SIGRTMIN+3

# Install packages for building
RUN apt-get update && \
    apt-get install -y sudo git make hasher hasher-priv mkimage mkimage-preinstall mki-build qemu-user-static-binfmt f2fs-tools && \
    apt-get clean -y

# Remove !container from hasher-privd service
RUN sed -i "s|ConditionVirtualization=!container|#ConditionVirtualization=!container|" \
    /usr/lib/systemd/system/hasher-privd.service

# Add builder user and add users to sudoers
RUN useradd -m -r -s /bin/bash -G wheel builder && \
    echo -e 'builder ALL=(ALL) NOPASSWD: ALL\nroot ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Hasher
RUN mkdir -p /home/builder/.hasher /home/builder/hasher
RUN echo -e 'tmpfs /dev/shm tmpfs defaults 0 0\n' >> /etc/hasher-priv/fstab
RUN echo -e 'allow_ttydev=yes\nallowed_mountpoints=/proc,/dev/pts,/dev/console' >> /etc/hasher-priv/system
RUN echo -e "def_repo=/home/builder/hasher\nknown_mountpoints=/dev/pts,/proc,/dev/console\nallowed_mountpoints=/dev/pts,/proc,/dev/console\npackager=\"$(rpm --eval %packager)\"\nexport GCC_USE_CCACHE=1\n" >> /home/builder/.hasher/config

# mkimage
RUN mkdir -p /home/builder/.mkimage
RUN echo -e 'CLEAN = 1\nDEBUG = 1\nREPORT = 1\nNO_SYMLINK = 1\n' > /home/builder/.mkimage/profiles.mk

# Add user to hasher groups
RUN hasher-useradd builder

# Enable hasher-privd service
RUN ln -s /usr/lib/systemd/system/hasher-privd.service /etc/systemd/system/multi-user.target.wants/

CMD ["/sbin/init"]
