# Load essential files:
emulate sh
[ -f /etc/profile ] && . /etc/profile
[ -f "$HOME"/.profile ] && . "$HOME"/.profile

emulate zsh

# eliminates duplicates in *paths
typeset -gU cdpath fpath path

# Zsh search path for executable
path=(
  /usr/local/{bin,sbin}
  $path
)