name: Build Distro

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run build script
        run: ./main.sh

      - name: Fix /workspace permissions
        run: |
          sudo chown -R runner:runner ${{ github.workspace }}/out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: alt-mobile
          path: ${{ github.workspace }}/out/
          if-no-files-found: error

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ${{ github.workspace }}/out/build.log
          if-no-files-found: warn

      # Шаг для деплоя файлов в Yandex Object Storage
      - name: Deploy to Yandex Object Storage
        uses: povetek/yandex-object-storage-action@v3
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          path: out
          clear: true
